[package]
name = "basic-spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
reqwest = "0.12.4"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = {version = "1.0.117", features = ["std"]}

